document.write('<div id="lmenu">');
document.write('<div id="lmenu_header">');
document.write('Contents');
document.write('</div>');
document.write('<ul id="lmenu_body">');
document.write('<li><a href="index.html">Linux</a></li>');
document.write('<li><a href="index.html">Emacs</a></li>');
document.write('<li><a href="index.html">Vi</a></li>');
document.write('<li><a href="index.html">make</a></li>');
document.write('</ul>');
document.write('</div>');
